---
- name: Create users and keys
  hosts: all
  become: true
  tasks:
    - name: Create ansible user
      tags: always
      user:
        name: ansible
        groups: root
    
    - name: Add ssh key for ansible user
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICmxbkrQpxCqKV7e2AT61Vkl0APcQSjZ6e9aB6fpdLz6 ansible user"

    - name: add sudoers file for ansible user
      tags: always
      copy:
        src: files/ansible_sudo
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440